config/routes.rb
Rails.application.routes.draw do


  root 'golden_idea/application#index'
  get 'questions/search' => 'questions#search'
  resources :questions do
    post 'upload_img', on: :collection
    get  'advanced_search', on: :collection
    get  'praise', on: :member
    get  'rubbish', on: :member
  end
  resources :categorys

  resource :chatbot do
    get 'get_answer', on: :collection
  end
  resources :links do
    get 'display_list', on: :collection
    get 'display_icon', on: :collection
    get 'code_scan', on: :collection
  end

  resources :departments do
    get 'update_department', on: :collection
  end

  resources :employees do
    get 'update_employee', on: :collection
    get 'phone_number', on: :collection
    post 'set_phone_number',on: :member
    get 'show_phone_number',on: :collection
    post 'set_my_phone_number',on: :collection
    get 'set_my_phone_number_page',on: :collection
    # 下面是图书管理相关
    get 'borrow_record',       on: :member
    get 'return_record',       on: :member
    get 'borrow_book',         on: :member
    get 'book_praise_rubbish', on: :member
    get 'book_comment',        on: :member
    # 下面是图书管理相关
    get 'golden_ideas',        on: :member
    get 'exchange_records',    on: :member
    get 'assign_score_records',    on: :member
    get 'score',    on: :member
    get 'score_lists',    on: :collection
  end

  resources :apis do
    post 'getuserid', on: :collection
    post 'get_userinfo', on: :collection
    get 'get_department', on: :collection
    get 'jsapi_oauth', on: :collection
    get 'send_message', on: :collection
  end

  resources :expresses do
    post 'batch_create', on: :collection
    get 'statistics',on: :collection
  end

  resources :books do
    resources :comments
    get 'index_admin', on: :collection
    get 'search',      on: :collection
    get 'praise',      on: :member
    get 'rubbish',     on: :member
    get 'borrow_view', on: :member
    post 'borrow',     on: :member
    get 'assign_view', on: :member
    post 'assign',     on: :member
    get 'return_book', on: :member
    get 'recycle_book', on: :member
    get 'continue_borrow', on: :member
    #批量导入
    post 'import',     on: :collection
    get  'export',     on: :collection
    #所有评论
    get  'all_comments',on: :member
    #扫描条形码
    get 'scan_barcode', on: :collection
    get 'scan_barcode_insert_isbn', on: :collection
  end
  resources :book_classifications do
    get 'index_admin', on: :collection
    get 'show_admin',  on: :member
  end

  get '/library' => 'library#index' #图书管理首页
  get '/library/borrow_books' => 'library#borrow_books' #图书管理正在被借阅
  get '/library/borrow_records' => 'library#borrow_records' #图书管理借阅记录
  get '/library/praise_rubbishs' => 'library#praise_rubbishs' #图书管理评价
  get '/library/comments' => 'library#comments' #图书管理评论
  get '/library/return_records' => 'library#return_records' #图书管理归还记录

  resources :attachments

  # 下面是金点子相关
  get '/golden_idea' => 'golden_idea/application#index'
  get '/golden_idea_good_exchange_records' => 'golden_idea/application#exchange_records'
  get '/golden_idea_assign_score_records' => 'golden_idea/application#assign_score_records'
  get '/golden_idea_employee_score_order' => 'golden_idea/application#employee_score_order'
  get '/golden_idea_score_order' => 'golden_idea/application#golden_idea_score_order'
  get '/golden_idea_user_requests' => 'golden_idea/application#user_requests'
  get '/golden_idea_dashboard' => 'golden_idea/application#dashboard'
  get '/golden_idea_score_standard' => 'golden_idea/application#golden_idea_score_standard'
  get '/golden_idea_template' => 'golden_idea/application#golden_idea_template'
  get '/golden_idea_search' => 'golden_idea/application#golden_idea_search'
  # 合理化建议
  get '/golden_idea_proposal' => 'golden_idea/application#golden_idea_proposal'
  post '/submit_golden_idea_proposal' => 'golden_idea/application#submit_golden_idea_proposal'
  namespace :golden_idea do
    resources :seasons do
      # get 'index_admin', on: :collection
      # get 'show_admin',  on: :member
    end
    resources :ideas do
      get 'search',      on: :collection
      # get 'index_admin', on: :collection
      get 'current_season_index', on: :collection
      # get 'current_season_index_admin', on: :collection
      # get 'show_admin',  on: :member
      # get 'edit_content',on: :member
      get 'score_view',  on: :member
      get 'employee_score_view',  on: :member
      post 'employee_score',  on: :member
      get 'import',     on: :collection
      post 'import_preview',     on: :collection
      get 'calculate_all',     on: :collection
    end
    resources :goods do
      get 'index_admin', on: :collection
      get 'show_admin',  on: :member
      get 'exchange_view',  on: :member
      patch 'exchange',  on: :member
    end
    resources :exchange_records do
      get 'complete',  on: :member
    end
    resources :suggests do
      get 'reply', on: :member
      get 'slide_show', on: :member
      get 'approve', on: :member
      get 'reject', on: :member
    end
    resources :score_records
  end

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  post "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/golden_idea.rb
module GoldenIdea
  def self.table_name_prefix
    'golden_idea_'
  end
end

app/models/golden_idea/assign_score_record.rb
module GoldenIdea
  class AssignScoreRecord < ApplicationRecord
    belongs_to :idea, optional: true
    belongs_to :employee
    before_create :set_site

    def set_site
      self.site = Employee.current_employee.site
    end
  end
end

app/controllers/golden_idea/application_controller.rb
module GoldenIdea
  class ApplicationController < ::ApplicationController
    layout 'golden_idea_new'
    # before_action :check_signed_in

    def index

    end

    def exchange_records
      @exchange_records = ExchangeRecord.where(site: Employee.current_employee.site).paginate page: params[:page], per_page: 8
    end

    def assign_score_records
      @assign_score_records = AssignScoreRecord.where(site: Employee.current_employee.site).paginate page: params[:page], per_page: 8
    end

    # 不放出链接
    def user_requests
      @user_requests = UserRequest.where('url like "%golden_idea%"').paginate page: params[:page], per_page: 8
    end

    def golden_idea_score_order
      # 这里没用， view中直接取得
      @golden_ideas = GoldenIdea::Idea.order(score: :desc)
    end

    def employee_score_order
    end

    def golden_idea_score_standard

    end

    def golden_idea_template
    end

    def golden_idea_proposal
    end

    def submit_golden_idea_proposal
      title = params[:proposal][:title]
      content = params[:proposal][:content]
      real_name = current_employee.name if params[:proposal][:real_name] == "1"

      NotificationMailer.proposal(title, content, real_name).deliver

      flash["success"] = "Submit successfully"
      redirect_to golden_idea_proposal_path
    end

    def dashboard
    end

    def golden_idea_search
    end

    # 确保已登录, 否则转向登录页面
    def check_signed_in
      unless signed_in? || request.env['HTTP_USER_AGENT'] =~ /DingTalk/
        flash[:warning] = "Please sign in first!"
        store_location    #如果没登录会跳转到登录页,在这保存原本想要访问的页面,登陆后返回
        redirect_to signin_path
      else
        Employee.current_employee = current_employee
      end
    end
  end
end

app/controllers/golden_idea/exchange_records_controller.rb
module GoldenIdea
  class ExchangeRecordsController < ApplicationController
    def index
      @exchange_records = ExchangeRecord.where(status: "pending", site: current_employee.site)
      respond_to { |format|
        format.html
        format.xlsx { send_data ExchangeRecord.to_xlsx(@exchange_records).stream.string, filename: "exchange_records.xlsx", disposition: 'attachment' }
      }
    end

    def complete
      @exchange_records = ExchangeRecord.find(params[:id])
      if @exchange_records.update(status: "complete")
        flash["success"] = "Exchange successfully"
      else
        flash["error"] = "Exchange unsuccessfully"
      end
      redirect_to golden_idea_exchange_records_path
    end
  end
end

app/controllers/golden_idea/goods_controller.rb
module GoldenIdea
  class GoodsController < ApplicationController
    layout 'golden_idea_new'
    def index
      @goods = Good.where(site: Employee.current_employee.site).where("quantity > 0").ransack(params[:q]).result(distinct: true).paginate page: params[:page], per_page: 8
    end

    def index_admin
      @goods = Good.where(site: Employee.current_employee.site).paginate page: params[:page], per_page: 10
    end

    def new
      @good = Good.new
      render layout: false
    end

    def create
      @good = Good.create(good_params)
      redirect_to index_admin_golden_idea_goods_path
    end

    def edit
      @good = Good.find params[:id]
      render layout: false
    end

    def update
      @good = Good.find(params[:id])
      if @good.update_attributes(good_params)
        flash["success"] = "Edit successfully"
      else
        flash["error"] = "Error:#{@good.errors.full_messages}"
      end
      # redirect_to index_admin_golden_idea_ideas_path
      redirect_to request.referer
    end

    def show_admin
      @good = Good.find(params[:id])
    end

    def show
      @good = Good.find(params[:id])
    end

    def exchange_view
      @good = Good.find(params[:id])
      render layout: false
    end

    def exchange
      @good = Good.find(params[:id])
      quantity = Integer(params[:exchange_quantity])
      required_points = quantity * @good.score
      current_employee = Employee.current_employee
      current_employee_available_score = current_employee.available_score
      good_quantity = @good.quantity
      if current_employee_available_score >= required_points && good_quantity >= quantity
        if current_employee.update(available_score: (current_employee_available_score - required_points)) && @good.update(quantity: (good_quantity - quantity))
          ExchangeRecord.create(good_id: @good.id, employee_id:current_employee.id, quantity: quantity, used_score: required_points)
          flash[:success] = "Exchange successfully"
        else
          # return render js: "$('#exchange_form').prepend(<h5 style='text-align: center;'>兑换失败</h5>)"
          flash[:danger] = "Exchange unsuccessfully"
        end
      else
        # return render js: "$('#exchange_form').prepend('<h5 style=\'text-align: center;\'>您的积分不足或没有库存</h5>')"
        flash[:warning] = "Points shortage or not enough stock"
      end
      redirect_to request.referer
    end

    def destroy
      @good = Good.find(params[:id])

      if @good.exchange_records.present?
        flash["error"] = "#{@good.name}has the exchange records, can't be deleted"
      else
        if @good.destroy
          flash["success"] = "#{@good.name} delete successfully"
        else
          flash["error"] = "Delete unsuccessfully:#{@good.errors.full_messages}"
        end
      end
      redirect_to request.referer
    end

    private
      def good_params
        params.require(:golden_idea_good).permit(:name, :description, :avatar, :quantity, :score, :content)
      end
  end
end

app/controllers/golden_idea/ideas_controller.rb
module GoldenIdea
  class IdeasController < ApplicationController
    layout 'golden_idea_new'
    def index
      @golden_ideas = Idea.ransack(params[:q])
      @golden_ideas.sorts = sort_params || "id DESC"
      if params[:q] && params[:q][:proposer]
        sql = ''
        params[:q][:proposer].each do |p_id|
          sql += "find_in_set(#{p_id},proposer) or "
        end
        sql.slice!(-4, 4) if sql.present?
        @golden_ideas = @golden_ideas.result(distinct: true).where(sql)
      else
        @golden_ideas = @golden_ideas.result(distinct: true)
      end
      @golden_ideas = @golden_ideas.paginate page: params[:page], per_page: 10

      respond_to { |format|
        format.html
        format.xlsx { send_data Idea.to_xlsx(@golden_ideas).stream.string, filename: "golden_ideas.xlsx", disposition: 'attachment' }
      }
    end

    #def index_admin
    #  @golden_ideas = Idea.ransack(params[:q]).result(distinct: true).paginate page: params[:page], per_page: 10
    #end

    def current_season_index
      @golden_ideas = Idea.where(season_id: Season.where(site: current_employee.site).last.id, site: current_employee.site)
      respond_to { |format|
        format.html
        format.xlsx { send_data Idea.to_xlsx(@golden_ideas).stream.string, filename: "golden_ideas.xlsx", disposition: 'attachment' }
      }
    end

    #def current_season_index_admin
    #  @golden_ideas = Idea.where(season_id: Season.last.id)
    #end

    def new
      @golden_idea = Idea.new
      # render layout: false
    end

    def create
      @golden_idea = Idea.new(golden_idea_params)
      if @golden_idea.save
        save_attachments if params[:attachment_files]
        save_sop_attachments if params[:sop_files]
        NotificationMailer.send_email_to_committee(@golden_idea).deliver
        flash["success"] = "Golden Idea create successfully"
        redirect_to golden_idea_idea_path(@golden_idea)
      else
        render :new
      end
    end

    def edit
      @golden_idea = Idea.find params[:id]
      # render layout: false
    end

    #def edit_content
    #  @golden_idea = Idea.find params[:id]
    #end

    def update
      @golden_idea = Idea.find(params[:id])
      if @golden_idea.update_attributes(golden_idea_params)
        save_attachments if params[:attachment_files]
        save_sop_attachments if params[:sop_files]
        flash["success"] = "Edit successfully"
        redirect_to golden_idea_idea_path(@golden_idea)
      else
        flash["error"] = "Edit unsuccessfully:#{@golden_idea.errors.full_messages}"
        render :edit
      end
    end

    def show
      @golden_idea = Idea.find(params[:id])
      @score_record = @golden_idea.score_records.find_by_employee_id(current_employee.id)
      @score_record ||= @golden_idea.score_records.new
    end

    #def show_admin
    #  @golden_idea = Idea.find(params[:id])
    #  # @golden_ideas = @season.golden_ideas
    #end

    def score_view
      @golden_idea = Idea.find params[:id]
      render layout: false
    end

    def score
      @golden_idea = Idea.find params[:id]
      render layout: false
    end

    def employee_score_view
      @golden_idea = Idea.find params[:id]
      render layout: false
    end

    def employee_score
      @golden_idea = Idea.find params[:id]
      employees = params[:employees]
      flash[:success] = "Assign point successfully"
      employees.each do |i, v|
        if Employee.find(i).assign_score(v.to_i)
          AssignScoreRecord.create(employee_id: i, idea_id: params[:id], score: v)
        else
          flash[:error] = "Assign point unsuccessfully"
        end
      end
      redirect_to golden_idea_idea_path(@golden_idea)
    end

    def destroy
      @golden_idea = Idea.find(params[:id])
      @golden_idea.destroy

      redirect_to current_season_index_golden_idea_ideas_path
    end

    def search
      @golden_ideas = Idea.search_name_by_token params[:term]
      @golden_ideas_size = @golden_ideas.size
      respond_to do |format|
        format.js { render :show }
      end
    end

    #批量上传
    # def import
      # if !params[:import][:file]
        # redirect_to golden_idea_ideas_path, alert: "You need select a file"
      # else
        # Idea.import(params[:import][:file])
        # redirect_to golden_idea_ideas_path, notice: "导入成功"
      # end
    # end

    def import_preview
      if !params[:import][:file]
        redirect_to golden_idea_ideas_path, alert: "You need select a file"
      else
        @ideas = Idea.import_preview(params[:import][:file])
        @ideas_cache_key = "ideas_#{SecureRandom.hex}"
        Rails.cache.write(@ideas_cache_key, @ideas, expires_in: 1.days)
      end
    end

    def import
      cr, er = 0, 0
      @ideas = Rails.cache.read(params[:cache_key])
      @ideas.map do |t|
        t.save ? cr += 1 : er += 1
      end
      Rails.cache.delete(params[:cache_key])
      info = (er == 0) ? :success : :danger
      flash[info] = "success: " + cr.to_s  + " error: " + er.to_s
      redirect_to current_season_index_golden_idea_ideas_url
    end

    # 计算本期所有已完成的得分
    def calculate_all
      @golden_ideas = Idea.where(season_id: Season.where(site: current_employee.site).last.id, score: nil, site: current_employee.site)
      @golden_ideas.each do |idea|
        if idea.score_records.length > 3
          scores = idea.score_records.map(&:score)
          scores = scores.sort.slice(1..-2)
          idea.update(score: scores.sum/scores.length)
        end
      end

      flash["success"] = "Score successfully"
      redirect_to current_season_index_golden_idea_ideas_path
    end

    private
      def golden_idea_params
        params.require(:golden_idea_idea).permit(:title, :category, {:proposers => []}, :department, :description, :content, :score, :status, :reporter_id, :is_involve_sop)
      end
  end
end

app/helpers/golden_idea/application_helper.rb
module GoldenIdea::ApplicationHelper
end

app/helpers/golden_idea/exchange_records_helper.rb
module GoldenIdea::ExchangeRecordsHelper
end

app/helpers/golden_idea/goods_helper.rb
module GoldenIdea::GoodsHelper
end

app/helpers/golden_idea/ideas_helper.rb
module GoldenIdea::IdeasHelper
end

app/helpers/golden_idea/score_records_helper.rb
module GoldenIdea::ScoreRecordsHelper
end

app/views/golden_idea/ideas/_form.html.erb
<div class="control-group">
  <label class="control-label" for="basicinput">标题</label>
  <div class="controls">
    <%= f.text_field  :title, placeholder: "金点子名称", class: "span8" %>
  </div>
</div>
<div class="control-group">
  <label class="control-label" for="basicinput">分类</label>
  <div class="controls">
    <%= f.select  :category, [['Non-Technology', 'Non-Technology'],['Technology', 'Technology']], include_blank: false, placeholder: "Type something here...", class: "span8" %>
  </div>
</div>
<div class="control-group">
  <label class="control-label" for="basicinput">主讲人</label>
  <div class="controls">
    <%#= f.select  :reporter_id, options_for_select(Employee.all.collect { |e| [ e.name, e.id ] }, :selected => selected), {:placeholder => "Please select"}, {:multiple => true, :class => 'span8 select2'} %>
    <%= f.select  :reporter_id, Employee.where(site: current_employee.site).collect { |e| [ e.name, e.id ] }, include_blank: false, placeholder: "Type something here...", class: "span8" %>
  </div>
</div>
<div class="control-group">
  <label class="control-label" for="basicinput">提议人</label>
  <div class="controls">
    <% selected = f.object.proposers.split(',') if f.object.proposers.present?  %>
    <%= f.select  :proposers, options_for_select(Employee.where(site: current_employee.site).collect { |e| [ e.name, e.id ] }, :selected => selected), {:placeholder => "Please select"}, {:multiple => true, :class => 'span8 select2'} %>
  </div>
</div>
<div class="control-group">
  <label class="control-label" for="basicinput">部门</label>
  <div class="controls">
    <%= f.text_field  :department, placeholder: "多部门用&连接", class: "span8" %>
  </div>
</div>
<div class="control-group">
  <label class="control-label" for="basicinput">内容描述</label>
  <div class="controls">
    <%= f.text_area  :description, placeholder: "简单描述", class: "span8" %>
  </div>
</div>
<div class="control-group">
  <label class="control-label" for="basicinput">附件</label>
  <div class="controls">
    <%= file_field_tag "attachment_files[]", multiple: true, type: :file %>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('.select2').select2({tags: true});
  });
</script>

app/views/golden_idea/ideas/_result_list.html.erb
<% golden_ideas.each_with_hit do |record, hit| %>
  <% title = hit.highlight.title ? (raw hit.highlight.title[0]) : record.title %>
  <div class="list-group-item">
    <div class="row">
      <div class="col px-4">
        <div>
          <div class="float-right"><%= record.created_at %></div>
          <h4><a href="<%= golden_idea_idea_path(record.id) %>"><%= title %></a></h4>
          <p class="mb-0"><%= record.try :description %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/golden_idea/ideas/create.html.erb
<h1>Categorys#create</h1>
<p>Find me in app/views/categorys/create.html.erb</p>

app/views/golden_idea/ideas/current_season_index.html.erb
<% provide :active, "current_period" %>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><%= t 'menu.current_season_idea' %>-<%= GoldenIdea::Season.where(site: current_employee.site).last.name %>(<%= @golden_ideas.count %>)</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/golden_idea">Home</a></li>
            <li class="breadcrumb-item active"><%= t 'menu.current_season_idea' %></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <%= render "golden_idea/application/flash" %>

    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= t 'table.collector' %>:
          <% if GoldenIdea::Season.where(site: current_employee.site).last.collecters.present? %>
            <% GoldenIdea::Season.where(site: current_employee.site).last.collecters.split(',').each do |u_id| %>
              <% user = Employee.find(u_id) %>
              <%= link_to user.name, user %>
            <% end %>
          <% end %>
          <div class="mt-2 mb-2">
            <% if signed_in? && current_employee.is_golden_idea_admin? %>
              <!--批量上传表单-->
              <%= form_for :import, url: import_preview_golden_idea_ideas_path, method: 'post', html:{ multipart: true, style: "display: none;" } do |f| %>
                <%= f.file_field :file, id: "upload-file-input" %>
                <%= f.submit '', id: "file-submit" %>
              <% end %>
              <%= link_to t('import'), "javascript:void(0);", class: "btn btn-sm btn-primary", id: "upload-file-btn", title: "You can click export to get the import template first" %>
              <%= link_to t('export'), current_season_index_golden_idea_ideas_path(format: :xlsx, params: request.query_parameters), class: "btn btn-sm btn-info" %>
              <% if ['刘春良', '徐梦婷', 'Brian Hulsebus', '方雄', '钱晶', '李娜'].include?(current_employee.name) %>
                <%= link_to t('calculate_all'), calculate_all_golden_idea_ideas_path, class: "btn btn-sm btn-info" %>
              <% end %>
            <% end %>
            <%= link_to t('new'), new_golden_idea_idea_path, class: "btn btn-sm btn-warning" %>
          </div>
        </h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
              <tr>
                <th style="width: 5%"><%= t 'table.category' %></th>
                <th style="width: 15%"><%= t 'table.title' %></th>
                <th style="width: 5%"><%= t 'table.speaker' %></th>
                <th style="width: 10%"><%= t 'table.proposer' %></th>
                <th style="width: 5%"><%= t 'table.department' %></th>
                <th style="width: 10%" class="text-center"><%= t 'table.status' %></th>
                <th style="width: 35%"><%= t 'table.description' %></th>
                <th style="width: 5%"><%= t 'table.score' %></th>
                <th style="width: 10%"></th>
              </tr>
            </thead>
            <tbody>
              <% @golden_ideas.each do |golden_idea| %>
                <tr class="" style="background: <%= is_transfer?(golden_idea) %>;">
                    <td><%= golden_idea.category %></td>
                    <td><%= link_to golden_idea.title, golden_idea_idea_path(golden_idea) %></td>
                    <td><%= golden_idea.reporter.try :name %></td>
                    <td class="project_progress">
                      <% if golden_idea.proposers.present? %>
                        <% golden_idea.proposers.split(',').each do |u_id| %>
                          <% user = Employee.find(u_id) %>
                          <%= link_to user.name, user %>
                        <% end %>
                      <% end %>
                    </td>
                    <td><%= golden_idea.department %></td>
                    <td class="project-state">
                      <% if golden_idea.status == "complete" %>
                        <span class="badge badge-success"><%= golden_idea.status %></span>
                      <% else %>
                        <span class="badge badge-warning"><%= golden_idea.status %></span>
                      <% end %>
                    </td>
                    <td title="<%= golden_idea.description %>" data-mtpis="<%= golden_idea.description %>"><%= truncate(golden_idea.description, length: 20) %></td>
                    <td>
                      <%= golden_idea.score %>
                      <% if signed_in? && current_employee.is_golden_idea_score? %>
                        <% score_record =  golden_idea.score_records.find_by_employee_id(current_employee.id) %>
                        <% if score_record.present? %>
                          <%= "#{score_record.benefit}/#{score_record.cost}/#{score_record.risk}" %>
                        <% else %>
                          <%= "0/0/0" %>
                        <% end %>
                      <% end %>
                    </td>
                    <td class="project-actions text-right">
                      <% if current_employee.is_golden_idea_admin? %>
                        <%= link_to t('edit'), edit_golden_idea_idea_path(golden_idea), class: "btn btn-info btn-sm" %>
                        <%= link_to t('delete'), golden_idea_idea_path(golden_idea), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" %>
                      <% elsif golden_idea.is_edit?(current_employee.id) %>
                        <%= link_to t('edit'), edit_golden_idea_idea_path(golden_idea), class: "btn btn-primary btn-sm" %></td>
                      <% end %>
                    </td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/golden_idea/ideas/employee_score_view.html.erb
<%= form_tag employee_score_golden_idea_idea_path(@golden_idea), { class: "form-horizontal row-fluid", id: "employee_score_form" } do -%>
  <% @golden_idea.proposers.split(",").each do |employee_id| %>
    <% employee = Employee.find(employee_id) %>
    <div class="control-group">
      <label class="control-label" for="basicinput"><%= employee.name %></label>
      <div class="controls">
        <input placeholder="<%= t 'form.score' %>" class="span8" type="text" name="employees[<%= employee.id %>]">
      </div>
    </div>
  <% end %>
<% end -%>

app/views/golden_idea/ideas/score_view.html.erb
<%= form_for @golden_idea, url: golden_idea_idea_path(@golden_idea), html: { class: "form-horizontal row-fluid", id: "golden_idea_score_form", enctype: "multipart/form-data" }  do |f| %>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label"><%= t 'form.score' %></label>
    <div class="col-sm-10">
      <%= f.text_field  :score, placeholder: "Type something here...", class: "form-control" %>
    </div>
  </div>
<% end %>

app/views/golden_idea/ideas/show.js.erb
<% if @golden_ideas.any? %>
   $("#list-group").children().remove();
   $("#list-group").append("<%= j render('result_list', golden_ideas: @golden_ideas) %>");
<% else %>
   $("#list-group").children().remove();
<% end %>