config/routes.rb
Rails.application.routes.draw do


  root 'golden_idea/application#index'
  get 'questions/search' => 'questions#search'
  resources :questions do
    post 'upload_img', on: :collection
    get  'advanced_search', on: :collection
    get  'praise', on: :member
    get  'rubbish', on: :member
  end
  resources :categorys

  resource :chatbot do
    get 'get_answer', on: :collection
  end
  resources :links do
    get 'display_list', on: :collection
    get 'display_icon', on: :collection
    get 'code_scan', on: :collection
  end

  resources :departments do
    get 'update_department', on: :collection
  end

  resources :employees do
    get 'update_employee', on: :collection
    get 'phone_number', on: :collection
    post 'set_phone_number',on: :member
    get 'show_phone_number',on: :collection
    post 'set_my_phone_number',on: :collection
    get 'set_my_phone_number_page',on: :collection
    # 下面是图书管理相关
    get 'borrow_record',       on: :member
    get 'return_record',       on: :member
    get 'borrow_book',         on: :member
    get 'book_praise_rubbish', on: :member
    get 'book_comment',        on: :member
    # 下面是图书管理相关
    get 'golden_ideas',        on: :member
    get 'exchange_records',    on: :member
    get 'assign_score_records',    on: :member
    get 'score',    on: :member
    get 'score_lists',    on: :collection
  end

  resources :apis do
    post 'getuserid', on: :collection
    post 'get_userinfo', on: :collection
    get 'get_department', on: :collection
    get 'jsapi_oauth', on: :collection
    get 'send_message', on: :collection
  end

  resources :expresses do
    post 'batch_create', on: :collection
    get 'statistics',on: :collection
  end

  resources :books do
    resources :comments
    get 'index_admin', on: :collection
    get 'search',      on: :collection
    get 'praise',      on: :member
    get 'rubbish',     on: :member
    get 'borrow_view', on: :member
    post 'borrow',     on: :member
    get 'assign_view', on: :member
    post 'assign',     on: :member
    get 'return_book', on: :member
    get 'recycle_book', on: :member
    get 'continue_borrow', on: :member
    #批量导入
    post 'import',     on: :collection
    get  'export',     on: :collection
    #所有评论
    get  'all_comments',on: :member
    #扫描条形码
    get 'scan_barcode', on: :collection
    get 'scan_barcode_insert_isbn', on: :collection
  end
  resources :book_classifications do
    get 'index_admin', on: :collection
    get 'show_admin',  on: :member
  end

  get '/library' => 'library#index' #图书管理首页
  get '/library/borrow_books' => 'library#borrow_books' #图书管理正在被借阅
  get '/library/borrow_records' => 'library#borrow_records' #图书管理借阅记录
  get '/library/praise_rubbishs' => 'library#praise_rubbishs' #图书管理评价
  get '/library/comments' => 'library#comments' #图书管理评论
  get '/library/return_records' => 'library#return_records' #图书管理归还记录

  resources :attachments

  # 下面是金点子相关
  get '/golden_idea' => 'golden_idea/application#index'
  get '/golden_idea_good_exchange_records' => 'golden_idea/application#exchange_records'
  get '/golden_idea_assign_score_records' => 'golden_idea/application#assign_score_records'
  get '/golden_idea_employee_score_order' => 'golden_idea/application#employee_score_order'
  get '/golden_idea_score_order' => 'golden_idea/application#golden_idea_score_order'
  get '/golden_idea_user_requests' => 'golden_idea/application#user_requests'
  get '/golden_idea_dashboard' => 'golden_idea/application#dashboard'
  get '/golden_idea_score_standard' => 'golden_idea/application#golden_idea_score_standard'
  get '/golden_idea_template' => 'golden_idea/application#golden_idea_template'
  get '/golden_idea_search' => 'golden_idea/application#golden_idea_search'
  # 合理化建议
  get '/golden_idea_proposal' => 'golden_idea/application#golden_idea_proposal'
  post '/submit_golden_idea_proposal' => 'golden_idea/application#submit_golden_idea_proposal'
  namespace :golden_idea do
    resources :seasons do
      # get 'index_admin', on: :collection
      # get 'show_admin',  on: :member
    end
    resources :ideas do
      get 'search',      on: :collection
      # get 'index_admin', on: :collection
      get 'current_season_index', on: :collection
      # get 'current_season_index_admin', on: :collection
      # get 'show_admin',  on: :member
      # get 'edit_content',on: :member
      get 'score_view',  on: :member
      get 'employee_score_view',  on: :member
      post 'employee_score',  on: :member
      get 'import',     on: :collection
      post 'import_preview',     on: :collection
      get 'calculate_all',     on: :collection
    end
    resources :goods do
      get 'index_admin', on: :collection
      get 'show_admin',  on: :member
      get 'exchange_view',  on: :member
      patch 'exchange',  on: :member
    end
    resources :exchange_records do
      get 'complete',  on: :member
    end
    resources :suggests do
      get 'reply', on: :member
      get 'slide_show', on: :member
      get 'approve', on: :member
      get 'reject', on: :member
    end
    resources :score_records
  end

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  post "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  cattr_accessor :current_employee

  belongs_to :department, optional: true
  # has_many :consumablerecords
  # has_many :attached_files, ->{ where( attached_files: { target_class: "authorizationservices" } ) }, :foreign_key => :target_id
  has_many :books, :foreign_key => :borrower_id
  has_many :borrow_records
  has_many :return_records
  has_many :comments
  has_many :count_records, ->{ where( count_records: { target_class: "book" } ) }
  has_many :exchange_records, class_name: "GoldenIdea::ExchangeRecord"
  has_many :assign_score_records, class_name: "GoldenIdea::AssignScoreRecord"

  scope :top_5, ->{order(score: :desc)}
  # def self.current_employee
  #   Thread.current[:employee]
  # end
  #
  # def self.current_employee=(employee)
  #   Thread.current[:employee] = employee
  # end

  #ldap登录
  def self.from_omniauth(auth)
    employee = Employee.find_or_create_by(email: auth.info.email) do |employee|
      employee.name = auth.info.name
      employee.email = auth.info.email
      employee.position = auth.info.title
      employee.active = 1
      employee.site = auth.extra.raw_info.l.last
    end
  end

  def golden_ideas
    GoldenIdea::Idea.where("find_in_set(#{id},proposer)")
  end

  def department_name
    department.try(:name)
  end

  def annual_blessing(is_manager=false)
    return if hired_date.blank?
    hired_year, hired_month, hired_day = hired_date.year, hired_date.month, hired_date.day
    current_year, current_month, current_day = Date.today.year, Date.today.month, Date.today.day

    if current_month == hired_month && current_day == hired_day
      if is_manager
        send_annual_blessing_notificaion(current_year - hired_year)
      else
        send_annual_blessing_notificaion_to_chunliang(current_year - hired_year)
      end
    end
  end

  def send_annual_blessing_notificaion(number)
    accessToken = AuthService.new.getAccessToken()
    data = {
      "chatid":'chat9b2fe210aee984aa0f46fb4611afc144',
      "agentid":180734473,
      "msgtype":"text",
      "text": {
        "content": "恭喜 #{name}入职#{number}周年"
      }
    }
    msg = MessageService.new.send_chat(accessToken,data)
    if msg.code == 200
      LogService.i("[notification_send] SUC: 员工祝贺发送成功,姓名:#{self.name}")
    else
      LogService.e("[notification_send] ERR: 员工祝贺发送失败,姓名:#{self.name}")
    end
  end

  def send_annual_blessing_notificaion_to_chunliang(number)
    accessToken = AuthService.new.getAccessToken()
    data = {
      "touser":130841175621040386,
      "agentid":180734473,
      "msgtype":"text",
      "text": {
        "content": "恭喜 #{name}入职#{number}周年"
      }
    }
    msg = MessageService.new.send(accessToken,data)
    if msg.code == 200
      LogService.i("[notification_send] SUC: 员工祝贺发送成功,姓名:#{self.name}")
    else
      LogService.e("[notification_send] ERR: 员工祝贺发送失败,姓名:#{self.name}")
    end
  end

  # 金点子相关
  GoldenIdeaMembers =  ["任帆", "卢兴潮", "魏力", "何沙", "胡灶顺", "徐梦婷", "陈艳莉", "路传伟", "郭森良", "曾鹏", "杨娜", "葛江燕", "张鑫", "谷丽娟", "邢天棋", "梅慧敏", "袁冰", "邵丹平", "陈俊刚", "黄磊", "钱晶", "张晶晶", "王慧", "应宇倩", "童川", "方雄", "Brian Hulsebus", "Lisong Guo", "郑伊婷", "刘春良", "姜涛", "马慧敏", "李颖洁", "李娜", "王洁茹"]

  # 打分的人
  GoldenIdeaScoreMembers =  ["钱晶", "徐梦婷", "赵威", "路传伟", "应宇倩", "张晶晶", "童川", "邢天棋", "曾鹏", "陈艳莉", "何沙", "卢兴潮", "任帆", "田斌", "王慧", "张鑫", "王标", "张承丽", "马纯", "庄海霁", "陈俊刚", "于君丽", "金钱斌", "陈卿", "刘青新", "葛挺", "方玮", "沈薇薇", "谢雯", "郭献强", "李晓丽", "谭兴梅", "张昕霞", "马妍", "张扬扬 Adam Zhang", "蒋忠根", "方雄", "胡勇", "Brian Hulsebus", "Lisong Guo", "郑伊婷", "刘春良", "姜涛", "马慧敏", "李颖洁", "李娜", "王洁茹"]

  def assign_score(assign_score)
    return false if assign_score.blank?

    update(score: (score + assign_score), available_score: (available_score + assign_score))
  end

  def is_golden_idea_admin?
    isadmin? || GoldenIdeaMembers.include?(name)
  end

  def is_golden_idea_score?
    GoldenIdeaScoreMembers.include?(name)
  end

  def self.all_user(orders)
    return Employee.where(site: Employee.current_employee.site) if orders.blank?

    Employee.where(site: Employee.current_employee.site).sort_by do |e|
      orders.index(e.id.to_s) || -1
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "Abcam123", only: [:index, :show_phone_number, :set_phone_number]
  before_action :init_locals, :only => :update_employee
  layout 'library', only: [:borrow_record, :return_record, :borrow_book, :book_praise_rubbish, :book_comment]

  def index
    @employees =  Employee.all.paginate page: params[:page], per_page: 15
  end

  def show
    #金点子在使用
    @employee =  Employee.find params[:id]
    render layout: 'golden_idea_new'
  end

  def phone_number
    @employees =  Employee.all
    render layout: false
  end

  def set_phone_number
    @employee =  Employee.find params[:id]
    if params[:type] == "extension_number"
      @employee.extension_number = params[:number]
    else
      @employee.linear_telephone = params[:number]
    end
    @employee.save
  end

  def show_phone_number
    @employees =  Employee.all.paginate page: params[:page], per_page: 15
  end

  def set_my_phone_number
    @employee =  Employee.find_by_name params[:employee_name]
    if @employee.blank?
      redirect_to set_my_phone_number_page_employees_path, notice: "姓名输入有误，请重新设置"
    else
      @employee.extension_number = params[:extension_number]
      @employee.linear_telephone = params[:linear_telephone]
      @employee.save
      redirect_to phone_number_employees_path
    end
  end

  def set_my_phone_number_page
    render layout: false
  end

  # 下面是图书管理相关
  def borrow_record
    @employee =  Employee.find params[:id]
    @borrow_records = @employee.borrow_records.paginate page: params[:page], per_page: 8
  end

  def return_record
    @employee =  Employee.find params[:id]
    @return_records = @employee.return_records.paginate page: params[:page], per_page: 8
  end

  def borrow_book
    @employee =  Employee.find params[:id]
    @books = @employee.books.paginate page: params[:page], per_page: 8
  end

  def book_praise_rubbish
    @employee =  Employee.find params[:id]
    @praise_rubbishs = @employee.count_records.paginate page: params[:page], per_page: 10
  end

  def book_comment
    @employee =  Employee.find params[:id]
    @comments = @employee.comments.paginate page: params[:page], per_page: 8
  end

  #金点子相关
  def golden_ideas
    @employee = Employee.find params[:id]
    @golden_ideas = @employee.golden_ideas
    render layout: "golden_idea_new"
  end

  def exchange_records
    @employee = Employee.find params[:id]
    @exchange_records = @employee.exchange_records
    render layout: "golden_idea_new"
  end

  def assign_score_records
    @employee = Employee.find params[:id]
    @assign_score_records = @employee.assign_score_records
    render layout: "golden_idea_new"
  end

  def score
    @employee = Employee.find params[:id]
    render layout: "golden_idea_new"
  end

  def score_lists
    @employees = Employee.ransack(params[:q]).result(distinct: true)
    @employees = @employees.paginate page: params[:page], per_page: 15
    render layout: "golden_idea"
  end

  def update_employee
    accessToken = @auth.getAccessToken() #获取token
    @msg = ""
    @departments = Department.all
    Employee.all.update_all(is_leave: 1)

    @departments.each do |department|
      department_employees = @user.list(accessToken,department.id)
      if department_employees["errmsg"] == "ok" && department_employees["errcode"] == 0
        department_employee_lists = department_employees["userlist"]

        department_employee_lists.each do |employee|
          if Employee.find_by_userid(employee["userid"]).blank?
            Employee.create(parse_employee(employee))
          else
            Employee.find_by_userid(employee["userid"]).update(parse_employee(employee))
          end
        end
        @msg = "#{@msg} - #{department.name}:#{department_employee_lists.count}"
      else
        @msg = "#{@msg} - #{department.name}:error"
      end
    end

    return render plain: @msg
  end

  def init_locals
    @auth = AuthService.new
    @user = UserService.new
  end

  def parse_employee(employee)
    hired_date = Time.at(employee["hiredDate"].present? ? employee["hiredDate"]/1000 : 0)
    {
      position: employee["position"],
      department_id: employee["department"].join(","),
      unionid: employee["unionid"],
      userid: employee["userid"],
      dingid: employee["dingId"],
      name: employee["name"],
      isleader: employee["isLeader"],
      active: employee["active"],
      openid: employee["openId"],
      avatar: employee["avatar"],
      isadmin: employee["isAdmin"],
      hired_date: hired_date,
      is_leave: 0
    }
  end
end

app/views/employees/assign_score_records.html.erb
<% provide :active, "my_point_list" %>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><%= t 'menu.my_point_list' %></h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/golden_idea">Home</a></li>
            <li class="breadcrumb-item active"><%= t 'menu.my_point_list' %></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <%= render "golden_idea/application/flash" %>
    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
              <tr>
                <th><%= t 'table.idea' %></th>
                <th><%= t 'table.point' %></th>
                <th><%= t 'table.date' %></th>
              </tr>
            </thead>
            <tbody>
              <% @assign_score_records.each do |assign_score_record| %>
                <tr>
                  <td>
                    <% if assign_score_record.idea.present? %>
                      <%= link_to assign_score_record.idea.title, golden_idea_idea_path(assign_score_record.idea) %>
                    <% else %>
                      合理化建议得分
                    <% end %>
                  </td>
                  <td><%= assign_score_record.score %></td>
                  <td><%= time_tag assign_score_record.created_at %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/employees/book_comment.html.erb
<div class="wrapper wrapper-library">
  <div class="container">
    <div class="row">
      <%= render 'library/left' %>
      <div class="span9">
        <div class="content">
          <div class="module">
            <div class="module-head">
              <h3>我的评论</h3>
            </div>
            <div class="module-body">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>书名</th>
                    <th>评价</th>
                    <th>时间</th>
                  </tr>
                </thead>
                <tbody>
                  <% @comments.each do |comment| %>
                    <tr>
                      <td><%= comment.id %></td>
                      <td><%= link_to comment.book_name, book_path(comment.book) %></td>
                      <td><%= comment.body %></td>
                      <td><%= comment.comment_time %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <%= will_paginate @comments, renderer: WillPaginate::ActionView::BlogLinkRenderer %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!--/.container-->
</div><!--/.wrapper-->

<style media="screen">
  .wrapper {
    min-height: 0;
  }
  .modal-backdrop, .modal-backdrop.fade.in {
    background: #000000;
    opacity: .8
  }
</style>

app/views/employees/book_praise_rubbish.html.erb
<div class="wrapper wrapper-library">
  <div class="container">
    <div class="row">
      <%= render 'library/left' %>
      <div class="span9">
        <div class="content">
          <div class="module">
            <div class="module-head">
              <h3>我的评价</h3>
            </div>
            <div class="module-body">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>书名</th>
                    <th>评价</th>
                    <th>时间</th>
                  </tr>
                </thead>
                <tbody>
                  <% @praise_rubbishs.each do |praise_rubbish| %>
                    <tr>
                      <td><%= praise_rubbish.id %></td>
                      <td><%= link_to praise_rubbish.book_name, book_path(praise_rubbish.book) %></td>
                      <td><%= praise_rubbish.type %></td>
                      <td><%= praise_rubbish.operation_time %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!--/.container-->
</div><!--/.wrapper-->

<style media="screen">
  .wrapper {
    min-height: 0;
  }
  .modal-backdrop, .modal-backdrop.fade.in {
    background: #000000;
    opacity: .8
  }
</style>

app/views/employees/borrow_book.html.erb
<div class="wrapper wrapper-library">
  <div class="container">
    <div class="row">
      <%= render 'library/left' %>
      <div class="span9">
        <div class="content">
          <div class="module">
            <div class="module-head">
              <h3>我的借阅</h3>
            </div>
            <div class="module-body">
              <%= render "library/flash" %>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>书名</th>
                    <th>作者</th>
                    <th>到期时间</th>
                    <th colspan="2">操作</th>
                  </tr>
                </thead>
                <tbody>
                  <% @books.each do |book| %>
                    <tr>
                      <td><%= book.id %></td>
                      <td><%= link_to book.name, book_path(book) %></td>
                      <td><%= book.author %></td>
                      <td><%= book.borrow_records.last.borrow_end %></td>
                      <td><%= link_to '还书', return_book_book_path(book), class: "btn btn-primary" %></td>
                      <td><%= link_to '续借', continue_borrow_book_path(book), class: "btn btn-primary", title: "续借默认是一个月时间" %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <%= will_paginate @books, renderer: WillPaginate::ActionView::BlogLinkRenderer %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!--/.container-->
</div><!--/.wrapper-->

<style media="screen">
  .wrapper {
    min-height: 0;
  }
  .modal-backdrop, .modal-backdrop.fade.in {
    background: #000000;
    opacity: .8
  }
</style>

app/views/employees/golden_ideas.html.erb
<% provide :active, "my_gi" %>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><%= t 'menu.my_idea' %></h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/golden_idea">Home</a></li>
            <li class="breadcrumb-item active"><%= t 'menu.my_idea' %></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <%= render "golden_idea/application/flash" %>
    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <div class="card-body p-0">
        <table class="table table-striped projects">
          <thead>
            <tr>
              <th><%= t 'table.category' %></th>
              <th><%= t 'table.title' %></th>
              <th><%= t 'table.proposer' %></th>
              <th><%= t 'table.department' %></th>
              <th><%= t 'table.description' %></th>
              <th><%= t 'table.score' %></th>
              <th><%= t 'table.action' %></th>
            </tr>
          </thead>
          <tbody>
            <% @golden_ideas.each do |golden_idea| %>
              <tr>
                <td><%= golden_idea.category %></td>
                <td><%= link_to golden_idea.title, golden_idea_idea_path(golden_idea) %></td>
                <td>
                  <% if golden_idea.proposers.present? %>
                    <% golden_idea.proposers.split(',').each do |u_id| %>
                      <% user = Employee.find(u_id) %>
                      <%= link_to user.name, user %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= golden_idea.department %></td>
                <td><%= golden_idea.description %></td>
                <td><%= golden_idea.score %></td>
                <td>
                  <% if golden_idea.is_edit?(current_employee.id) %>
                    <%= link_to t('edit'), edit_golden_idea_idea_path(golden_idea), class: "btn btn-sm btn-primary" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/employees/show.html.erb
<%
  rowno = ActiveRecord::Base.connection.execute("select rowno from (select id,score,(@rowno:=@rowno+1) as rowno from employees,(select (@rowno:=0)) b order by score desc) c where id = #{@employee.id};")
  rowno = Integer(rowno.to_a[0][0])
%>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Profile</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">User Profile</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <%= render "golden_idea/application/flash" %>
    <!-- Default box -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3">

          <!-- Profile Image -->
          <div class="card card-primary card-outline">
            <div class="card-body box-profile">
              <div class="text-center">
                <!--<img class="profile-user-img img-fluid img-circle" src="<%#= @employee.avatar %>" alt="<%#= @employee.name %>">-->
              </div>

              <h3 class="profile-username text-center"><%= @employee.name %></h3>

              <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                  <b><%= t 'current_ranking' %></b> <a class="float-right"><%= rowno %></a>
                </li>
                <li class="list-group-item">
                  <b><%= t 'total_point' %></b> <a class="float-right"><%= @employee.score %></a>
                </li>
                <li class="list-group-item">
                  <b><%= t 'available_point' %></b> <a class="float-right"><%= @employee.available_score %></a>
                </li>
                <li class="list-group-item">
                  <b><%= t 'site' %></b> <a class="float-right"><%= @employee.site %></a>
                </li>
                <li class="list-group-item">
                  <b><%= t 'email' %></b> <a class="float-right"><%= @employee.email %></a>
                </li>
              </ul>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->

        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="card">
            <div class="card-header p-2">
              <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link active" href="#golden_idea" data-toggle="tab"><%= t 'golden_idea' %></a></li>
                <li class="nav-item"><a class="nav-link" href="#exchange_record" data-toggle="tab"><%= t 'menu.point_exchange' %></a></li>
              </ul>
            </div><!-- /.card-header -->
            <div class="card-body">
              <div class="tab-content">
                <div class="active tab-pane" id="golden_idea">
                  <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th><%= t 'table.category' %></th>
                          <th><%= t 'table.title' %></th>
                          <th><%= t 'table.proposer' %></th>
                          <th><%= t 'table.department' %></th>
                          <th><%= t 'table.description' %></th>
                          <th><%= t 'table.score' %></th>
                          <th><%= t 'table.action' %></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @employee.golden_ideas.each do |golden_idea| %>
                          <tr>
                            <td><%= golden_idea.category %></td>
                            <td><%= link_to golden_idea.title, golden_idea_idea_path(golden_idea) %></td>
                            <td>
                              <% if golden_idea.proposers.present? %>
                                <% golden_idea.proposers.split(',').each do |u_id| %>
                                  <% user = Employee.find(u_id) %>
                                  <%= link_to user.name, user %>
                                <% end %>
                              <% end %>
                            </td>
                            <td><%= golden_idea.department %></td>
                            <td><%= golden_idea.description %></td>
                            <td><%= golden_idea.score %></td>
                            <% if golden_idea.is_edit?(@employee.id) %>
                              <td class="cell-btn align-right"><%= link_to 'Edit', edit_golden_idea_idea_path(golden_idea), class: "btn btn-sm btn-primary" %></td>
                            <% end %>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
                </div>
                <!-- /.tab-pane -->
                <div class="tab-pane" id="exchange_record">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th><%= t 'table.commodity' %></th>
                        <th><%= t 'table.quantity' %></th>
                        <th><%= t 'table.used_score' %></th>
                        <th><%= t 'table.date' %></th>
                        <th><%= t 'table.status' %></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @employee.exchange_records.each do |exchange_record| %>
                        <tr>
                          <td><%= exchange_record.good.name %></td>
                          <td><%= exchange_record.quantity %></td>
                          <td><%= exchange_record.used_score %></td>
                          <td><%= exchange_record.created_at %></td>
                          <td><%= exchange_record.status %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <!-- /.tab-pane -->
              </div>
              <!-- /.tab-content -->
            </div><!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->