config/routes.rb
Rails.application.routes.draw do


  root 'golden_idea/application#index'
  get 'questions/search' => 'questions#search'
  resources :questions do
    post 'upload_img', on: :collection
    get  'advanced_search', on: :collection
    get  'praise', on: :member
    get  'rubbish', on: :member
  end
  resources :categorys

  resource :chatbot do
    get 'get_answer', on: :collection
  end
  resources :links do
    get 'display_list', on: :collection
    get 'display_icon', on: :collection
    get 'code_scan', on: :collection
  end

  resources :departments do
    get 'update_department', on: :collection
  end

  resources :employees do
    get 'update_employee', on: :collection
    get 'phone_number', on: :collection
    post 'set_phone_number',on: :member
    get 'show_phone_number',on: :collection
    post 'set_my_phone_number',on: :collection
    get 'set_my_phone_number_page',on: :collection
    # 下面是图书管理相关
    get 'borrow_record',       on: :member
    get 'return_record',       on: :member
    get 'borrow_book',         on: :member
    get 'book_praise_rubbish', on: :member
    get 'book_comment',        on: :member
    # 下面是图书管理相关
    get 'golden_ideas',        on: :member
    get 'exchange_records',    on: :member
    get 'assign_score_records',    on: :member
    get 'score',    on: :member
    get 'score_lists',    on: :collection
  end

  resources :apis do
    post 'getuserid', on: :collection
    post 'get_userinfo', on: :collection
    get 'get_department', on: :collection
    get 'jsapi_oauth', on: :collection
    get 'send_message', on: :collection
  end

  resources :expresses do
    post 'batch_create', on: :collection
    get 'statistics',on: :collection
  end

  resources :books do
    resources :comments
    get 'index_admin', on: :collection
    get 'search',      on: :collection
    get 'praise',      on: :member
    get 'rubbish',     on: :member
    get 'borrow_view', on: :member
    post 'borrow',     on: :member
    get 'assign_view', on: :member
    post 'assign',     on: :member
    get 'return_book', on: :member
    get 'recycle_book', on: :member
    get 'continue_borrow', on: :member
    #批量导入
    post 'import',     on: :collection
    get  'export',     on: :collection
    #所有评论
    get  'all_comments',on: :member
    #扫描条形码
    get 'scan_barcode', on: :collection
    get 'scan_barcode_insert_isbn', on: :collection
  end
  resources :book_classifications do
    get 'index_admin', on: :collection
    get 'show_admin',  on: :member
  end

  get '/library' => 'library#index' #图书管理首页
  get '/library/borrow_books' => 'library#borrow_books' #图书管理正在被借阅
  get '/library/borrow_records' => 'library#borrow_records' #图书管理借阅记录
  get '/library/praise_rubbishs' => 'library#praise_rubbishs' #图书管理评价
  get '/library/comments' => 'library#comments' #图书管理评论
  get '/library/return_records' => 'library#return_records' #图书管理归还记录

  resources :attachments

  # 下面是金点子相关
  get '/golden_idea' => 'golden_idea/application#index'
  get '/golden_idea_good_exchange_records' => 'golden_idea/application#exchange_records'
  get '/golden_idea_assign_score_records' => 'golden_idea/application#assign_score_records'
  get '/golden_idea_employee_score_order' => 'golden_idea/application#employee_score_order'
  get '/golden_idea_score_order' => 'golden_idea/application#golden_idea_score_order'
  get '/golden_idea_user_requests' => 'golden_idea/application#user_requests'
  get '/golden_idea_dashboard' => 'golden_idea/application#dashboard'
  get '/golden_idea_score_standard' => 'golden_idea/application#golden_idea_score_standard'
  get '/golden_idea_template' => 'golden_idea/application#golden_idea_template'
  get '/golden_idea_search' => 'golden_idea/application#golden_idea_search'
  # 合理化建议
  get '/golden_idea_proposal' => 'golden_idea/application#golden_idea_proposal'
  post '/submit_golden_idea_proposal' => 'golden_idea/application#submit_golden_idea_proposal'
  namespace :golden_idea do
    resources :seasons do
      # get 'index_admin', on: :collection
      # get 'show_admin',  on: :member
    end
    resources :ideas do
      get 'search',      on: :collection
      # get 'index_admin', on: :collection
      get 'current_season_index', on: :collection
      # get 'current_season_index_admin', on: :collection
      # get 'show_admin',  on: :member
      # get 'edit_content',on: :member
      get 'score_view',  on: :member
      get 'employee_score_view',  on: :member
      post 'employee_score',  on: :member
      get 'import',     on: :collection
      post 'import_preview',     on: :collection
      get 'calculate_all',     on: :collection
    end
    resources :goods do
      get 'index_admin', on: :collection
      get 'show_admin',  on: :member
      get 'exchange_view',  on: :member
      patch 'exchange',  on: :member
    end
    resources :exchange_records do
      get 'complete',  on: :member
    end
    resources :suggests do
      get 'reply', on: :member
      get 'slide_show', on: :member
      get 'approve', on: :member
      get 'reject', on: :member
    end
    resources :score_records
  end

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  post "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <b class="copyright">&copy; 2018 Abcam - 10.8.1.36 </b> All rights reserved.
  </div>
</div>

app/views/shared/_header.html.erb

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <i class="icon-reorder shaded"></i>
      </a>

        <a class="brand" href="/">
          ABCAM
        </a>
      <% if params[:controller] != "sessions" %>
        <div class="nav-collapse collapse navbar-inverse-collapse">
          <ul class="nav nav-icons">
            <li class="active"><a href="<%= questions_path %>"><i class="icon-dashboard"></i></a></li>
            <li><a href="<%= advanced_search_questions_path %>"><i class="icon-eye-open"></i></a></li>
            <li><a href="<%= new_question_path %>"><i class="icon-bar-chart"></i></a></li>
            <li><a href="<%= categorys_path %>"><i class="icon-bold"></i></a></li>
          </ul>

          <form class="navbar-search pull-left input-append dropdown" action="/questions/search" accept-charset="UTF-8" data-remote="true" method="get" id="search-form" >
            <input type="text" class="span3" id="search_in_keyword" name="term" placeholder="搜索本站内容">
            <button class="btn" type="submit" id="search" value="Submit">
              <i class="icon-search"></i>
            </button>
            <input type="hidden" class="dropdown-toggle" data-toggle="dropdown">
            <ul class="dropdown-menu" style="width: 307px;" id="search-result">
            <!-- 这里是查询返回的内容 -->
            </ul>
          </form>




          <ul class="nav pull-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">问题 <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<%= questions_path %>">常见问题</a></li>
                <li><a href="<%= advanced_search_questions_path %>">高级搜索</a></li>
                <li><a href="<%= new_question_path %>">新建帮助</a></li>
                <li class="divider"></li>
                <li><a href="<%= categorys_path %>">问题分类</a></li>
              </ul>
            </li>

            <li><a href="#">
              在线客服
            </a></li>
            <li class="nav-user dropdown">
              <% if session[:admin] == 1%>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">管理员 <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<%= links_path %>">钉钉链接管理</a></li>
                  <li><a href="<%= display_list_links_path %>" target="_blank">钉钉链接显示</a></li>
                  <li><a href="<%= display_icon_links_path %>" target="_blank">钉钉图标选择</a></li>
                  <li class="divider"></li>
                  <li><a href="<%= signout_path %>">退出</a></li>
                </ul>
              <% else %>
                <a href="<%= signin_path %>">登录 </b></a>
              <% end %>
            </li>
          </ul>
        </div><!-- /.nav-collapse -->
      <% else %>
        <div class="nav-collapse collapse navbar-inverse-collapse">
          <ul class="nav pull-right">
            <li><a href="#">
            </a></li>
            <li><a href="#">
            </a></li>
          </ul>
        </div>
      <% end %>

    </div>
  </div><!-- /navbar-inner -->
</div><!-- /navbar -->

<script type="text/javascript">

  $("#search").on("click", function() {
  });
  $("#search-form").on("click", function() {
    //return false;
  });

  $("#search_in_keyword").on("input", function() {
    $("#search").click();
  });
</script>

<style>
  li strong {
    color: #eb592c;
  }
  .navbar #search-result li>a:hover {
    background: #f9f9f9;
    color: #555
  }
</style>

app/views/shared/_left.html.erb
<div class="span3">
  <div class="sidebar">

    <ul class="widget widget-menu unstyled">
      <li class="active">
        <a href="<%= questions_path %>">
          <i class="menu-icon icon-dashboard"></i>
          常见问题
        </a>
      </li>
      <li>
        <a href="<%= new_question_path %>">
          <i class="menu-icon icon-bullhorn"></i>
          新建帮助
        </a>
      </li>
      <li>
        <a href="<%= advanced_search_questions_path %>">
          <i class="menu-icon icon-inbox"></i>
          高级搜索
        </a>
      </li>

      <li>
        <a href="<%= categorys_path %>">
          <i class="menu-icon icon-tasks"></i>
          问题分类
          <b class="label orange pull-right">19</b>
        </a>
      </li>
    </ul><!--/.widget-nav-->

    <!-- <ul class="widget widget-menu unstyled">
        <li><a href="<%= links_path %>"><i class="menu-icon icon-bold"></i> 链接管理 </a></li>
        <li><a href="<%= display_list_links_path %>"><i class="menu-icon icon-book"></i> 钉钉链接显示 </a></li>
        <li><a href="form.html"><i class="menu-icon icon-paste"></i>Forms </a></li>
        <li><a href="table.html"><i class="menu-icon icon-table"></i>Tables </a></li>
        <li><a href="charts.html"><i class="menu-icon icon-bar-chart"></i>Charts </a></li>
    </ul> --><!--/.widget-nav-->

    <ul class="widget widget-menu unstyled">
      <% Category.all.each do |category| %>
        <li>
          <a class="collapsed" data-toggle="collapse" href="#togglePages_<%= category.id %>">
            <i class="menu-icon icon-cog"></i>
            <i class="icon-chevron-down pull-right"></i>
            <i class="icon-chevron-up pull-right"></i>
            <%= category.category_name %>
          </a>
          <ul id="togglePages_<%= category.id %>" class="collapse unstyled">
            <% category.questions.limit(5).each do |question| %>
              <li><a href="<%= question_path(question) %>"><i class="icon-paste"></i><%= question.title %></a></li>
            <% end %>
          </ul>
        </li>
      <% end %>


      <li><a href="/departments"><i class="menu-icon icon-group"></i>部门列表</a></li>
      <li><a href="/employees"><i class="menu-icon icon-user"></i>员工列表</a></li>
      <li><a href="/employees/phone_number"><i class="menu-icon icon-user"></i>通讯录</a></li>
      <li><a href="/employees/show_phone_number"><i class="menu-icon icon-user"></i>号码设置</a></li>
      <!-- <li>
        <a href="#">
          <i class="menu-icon icon-signout"></i>
          Logout
        </a>
      </li> -->
    </ul>

  </div><!--/.sidebar-->
</div><!--/.span3-->