config/routes.rb
Rails.application.routes.draw do


  root 'golden_idea/application#index'
  get 'questions/search' => 'questions#search'
  resources :questions do
    post 'upload_img', on: :collection
    get  'advanced_search', on: :collection
    get  'praise', on: :member
    get  'rubbish', on: :member
  end
  resources :categorys

  resource :chatbot do
    get 'get_answer', on: :collection
  end
  resources :links do
    get 'display_list', on: :collection
    get 'display_icon', on: :collection
    get 'code_scan', on: :collection
  end

  resources :departments do
    get 'update_department', on: :collection
  end

  resources :employees do
    get 'update_employee', on: :collection
    get 'phone_number', on: :collection
    post 'set_phone_number',on: :member
    get 'show_phone_number',on: :collection
    post 'set_my_phone_number',on: :collection
    get 'set_my_phone_number_page',on: :collection
    # 下面是图书管理相关
    get 'borrow_record',       on: :member
    get 'return_record',       on: :member
    get 'borrow_book',         on: :member
    get 'book_praise_rubbish', on: :member
    get 'book_comment',        on: :member
    # 下面是图书管理相关
    get 'golden_ideas',        on: :member
    get 'exchange_records',    on: :member
    get 'assign_score_records',    on: :member
    get 'score',    on: :member
    get 'score_lists',    on: :collection
  end

  resources :apis do
    post 'getuserid', on: :collection
    post 'get_userinfo', on: :collection
    get 'get_department', on: :collection
    get 'jsapi_oauth', on: :collection
    get 'send_message', on: :collection
  end

  resources :expresses do
    post 'batch_create', on: :collection
    get 'statistics',on: :collection
  end

  resources :books do
    resources :comments
    get 'index_admin', on: :collection
    get 'search',      on: :collection
    get 'praise',      on: :member
    get 'rubbish',     on: :member
    get 'borrow_view', on: :member
    post 'borrow',     on: :member
    get 'assign_view', on: :member
    post 'assign',     on: :member
    get 'return_book', on: :member
    get 'recycle_book', on: :member
    get 'continue_borrow', on: :member
    #批量导入
    post 'import',     on: :collection
    get  'export',     on: :collection
    #所有评论
    get  'all_comments',on: :member
    #扫描条形码
    get 'scan_barcode', on: :collection
    get 'scan_barcode_insert_isbn', on: :collection
  end
  resources :book_classifications do
    get 'index_admin', on: :collection
    get 'show_admin',  on: :member
  end

  get '/library' => 'library#index' #图书管理首页
  get '/library/borrow_books' => 'library#borrow_books' #图书管理正在被借阅
  get '/library/borrow_records' => 'library#borrow_records' #图书管理借阅记录
  get '/library/praise_rubbishs' => 'library#praise_rubbishs' #图书管理评价
  get '/library/comments' => 'library#comments' #图书管理评论
  get '/library/return_records' => 'library#return_records' #图书管理归还记录

  resources :attachments

  # 下面是金点子相关
  get '/golden_idea' => 'golden_idea/application#index'
  get '/golden_idea_good_exchange_records' => 'golden_idea/application#exchange_records'
  get '/golden_idea_assign_score_records' => 'golden_idea/application#assign_score_records'
  get '/golden_idea_employee_score_order' => 'golden_idea/application#employee_score_order'
  get '/golden_idea_score_order' => 'golden_idea/application#golden_idea_score_order'
  get '/golden_idea_user_requests' => 'golden_idea/application#user_requests'
  get '/golden_idea_dashboard' => 'golden_idea/application#dashboard'
  get '/golden_idea_score_standard' => 'golden_idea/application#golden_idea_score_standard'
  get '/golden_idea_template' => 'golden_idea/application#golden_idea_template'
  get '/golden_idea_search' => 'golden_idea/application#golden_idea_search'
  # 合理化建议
  get '/golden_idea_proposal' => 'golden_idea/application#golden_idea_proposal'
  post '/submit_golden_idea_proposal' => 'golden_idea/application#submit_golden_idea_proposal'
  namespace :golden_idea do
    resources :seasons do
      # get 'index_admin', on: :collection
      # get 'show_admin',  on: :member
    end
    resources :ideas do
      get 'search',      on: :collection
      # get 'index_admin', on: :collection
      get 'current_season_index', on: :collection
      # get 'current_season_index_admin', on: :collection
      # get 'show_admin',  on: :member
      # get 'edit_content',on: :member
      get 'score_view',  on: :member
      get 'employee_score_view',  on: :member
      post 'employee_score',  on: :member
      get 'import',     on: :collection
      post 'import_preview',     on: :collection
      get 'calculate_all',     on: :collection
    end
    resources :goods do
      get 'index_admin', on: :collection
      get 'show_admin',  on: :member
      get 'exchange_view',  on: :member
      patch 'exchange',  on: :member
    end
    resources :exchange_records do
      get 'complete',  on: :member
    end
    resources :suggests do
      get 'reply', on: :member
      get 'slide_show', on: :member
      get 'approve', on: :member
      get 'reject', on: :member
    end
    resources :score_records
  end

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  post "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book_classification.rb
class BookClassification < ApplicationRecord
  has_many :books

  def has_book?
    books.count > 1 ? true : false
  end
end

app/controllers/book_classifications_controller.rb
class BookClassificationsController < ApplicationController
  layout 'library'

  def index
    @book_classifications = BookClassification.all
  end

  def index_admin
    @book_classifications = BookClassification.all
  end

  def new
    @book_classification = BookClassification.new
    render layout: false
  end

  def create
    # render json: params[:book_classification][:book_classification_name]
    @book_classification = BookClassification.create(book_classification_params)
    redirect_to index_admin_book_classifications_path
  end

  def edit
    @book_classification = BookClassification.find(params[:id])
    render layout: false
  end

  def update
    @book_classification = BookClassification.find(params[:id])
    @book_classification.name = params[:book_classification][:name]
    @book_classification.save
    redirect_to index_admin_book_classifications_path
  end

  def show
    @book_classification = BookClassification.find(params[:id])
    @classification_books = @book_classification.books.paginate page: params[:page], per_page: 10
  end

  def show_admin
    @book_classification = BookClassification.find(params[:id])
    @classification_books = @book_classification.books.paginate page: params[:page], per_page: 8
  end

  def destroy
    @book_classification = BookClassification.find(params[:id])
    if @book_classification.has_book?
      flash["error"] = "分类下有图书禁止删除"
    else
      if @book_classification.destroy
        flash["success"] = "分类:#{@book_classification.name} 删除成功"
      else
        flash["error"] = "删除失败"
      end
    end
    redirect_to book_classifications_path
  end
  private
    def book_classification_params
      params.require(:book_classification).permit(:name)
    end

end

app/views/book_classifications/index.html.erb
<div class="wrapper wrapper-library">
  <div class="container">
    <div class="row">
      <%= render 'library/left' %>
      <div class="span9">
        <div class="content">
          <div class="module">
            <div class="module-head">
               <h3>图书分类</h3>
            </div>
            <div class="module-body">
              <%= render "library/flash" %>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>分类名</th>
                    <th>数量</th>
                  </tr>
                </thead>
                <tbody>
                  <% @book_classifications.each do |book_classification| %>
                    <tr>
                      <td><%= book_classification.id %></td>
                      <td><%= link_to book_classification.name, book_classification_path(book_classification) %></td>
                      <td><%= book_classification.books.count %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <div class="module-foot"></div>
          </div>
        </div><!--/.content-->
      </div><!--/.span9-->
    </div>
  </div><!--/.container-->
</div><!--/.wrapper-->

app/views/book_classifications/index_admin.html.erb
<div class="wrapper wrapper-library">
  <div class="container">
    <div class="row">
      <%= render 'library/left' %>

      <div class="span9">
        <div class="content">
          <div class="module">
            <div class="module-head">
               <h3>图书分类-管理</h3>
            </div>
            <div class="module-option clearfix">
                <div class="pull-right">
                   <%= link_to 'Create', new_book_classification_path, class: "btn btn-primary","data-toggle"=>"modal", "data-target"=>"#myModal" %>
                </div>
            </div>
            <div class="module-body">
              <%= render "library/flash" %>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>分类名</th>
                    <th>数量</th>
                    <th class="cell-btn align-right">操作</th>
                    <th class="cell-btn align-right"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @book_classifications.each do |book_classification| %>
                    <tr>
                      <td><%= book_classification.id %></td>
                      <td><%= link_to book_classification.name, show_admin_book_classification_path(book_classification) %></td>
                      <td><%= book_classification.books.count %></td>
                      <td class="cell-btn align-right"><%= link_to 'Edit', edit_book_classification_path(book_classification), class: "btn btn-mini btn-primary","data-toggle"=>"modal", "data-target"=>"#myModal" %></td>
                      <td class="cell-btn align-right"><%= link_to 'Del', book_classification_path(book_classification), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-mini btn-primary" %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div><!--/.content-->
      </div><!--/.span9-->
    </div>
  </div><!--/.container-->
</div><!--/.wrapper-->



<div class="modal fade production-task-model-config" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">x</button>
       <h3>编辑分类</h3>
    </div>
    <div class="modal-content">
      <div class="modal-body">
        <div style="width:10px;height:10px;"></div>
      </div>
    </div>
    <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
       <button type="submit" class="btn btn-primary" onclick="document.getElementById('create_book_classification_form').submit();">Submit</button>
    </div>
   </div>
</div>
<script>
  $("#myModal").on("hidden", function() {
    $(this).removeData("modal");
  });

  $('#closebtn').on('click', function(){
    $(".modal-body input[value='Save']").click();
    setTimeout("location.reload()",500);
  });
</script>

<style type="text/css">
.modal-backdrop, .modal-backdrop.fade.in {
  background: #000000;
  opacity: .8
}
</style>

app/views/book_classifications/new.html.erb
<%= form_for @book_classification, url: book_classifications_path, html: { class: "form-horizontal row-fluid", id: "create_book_classification_form" }  do |c| %>
  <div class="control-group">
    <label class="control-label" for="basicinput">Book Classification Name</label>
    <div class="controls">
      <%= c.text_field  :name, placeholder: "Type something here...", class: "span8" %>
    </div>
  </div>
<% end %>